# Generated by Django 2.0.5 on 2019-03-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='img_preview',
            field=models.TextField(default='https://previews.123rf.com/images/alekseyvanin/alekseyvanin1811/alekseyvanin181100948/111332068-unknown-phone-call-vector-icon-filled-flat-sign-for-mobile-concept-and-web-design-telephone-with-que.jpg'),
        ),
    ]
